version: '3.8'

services:
  dev-db:
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=retailify-erp-dev-db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
